### ISSUE TITLE
Not an Issue, Just wanted to Say Thanks

### ISSUE THREAD

**Issue by mike-mitchell** [cleesmith/unifiedbeat#1]
Stood up an instance of this filebeat in Docker today to support my Network Security Monitoring tool. Everything works great. just wanted to say thank you for creating this. I had been using various other tools and logstash to try and get the packet data from Snort into elasticsearch. This greatly simplifies things. 
Thanks again and let me know if there is any way I can help or contribute.

**Comment by cleesmith** [comment]
Great, I'm glad someone finds it useful other than the company I work for ... we have tried and coded just about everything you can imagine. I even coded something like unifiedbeat in Python called [Uni2EsPy](https://github.com/cleesmith/uni2espy), which works but uses [IdsTools](https://github.com/jasonish/py-idstools). We find Logstash a bit heavy to use all of the time, but it works and is flexible and is slow.

Most of the credit should go to Elastic Beats. I just wish they would slow down with their development changes ... as I can't keep up just doing this on the weekends. 

I am hoping to find the time replace Sguil, Squert, and ELSA with their Go equivalents, as these can be difficult to install unless you're using Security Onion (which we don't use).

Any help, feedback, or whatever is always welcomed.

**Comment by mike-mitchell** [comment]
I was actually using Uni2 previously. It was working well but this setup is way more efficient.
I started out the same way, I was trying to find a way to replace ELSA and Snorby in our environments. The ELK stack has worked pretty well after I figured out how to tune the indexes for the amount of data coming in. We are also sending BRO logs to ELK using elasticsearch. Hopefully their next release will include the python elasticsearch module.
If you don't mind me asking, what company do you work for?

On Jan 22, 2016 1:20 PM, chris <notifications@github.com> wrote:

Great, I'm glad someone finds it useful other than the company I work for ... we have tried and coded just about everything you can imagine. I even coded something like unifiedbeat in Python called Uni2EsPy<https://github.com/cleesmith/uni2espy>, which works but uses IdsTools<https://github.com/jasonish/py-idstools>. We find Logstash a bit heavy to use all of the time, but it works and is flexible and is slow.

Most of the credit should go to Elastic Beats. I just wish they would slow down with their development changes ... as I can't keep up just doing this on the weekends.

I am hoping to find the time replace Sguil, Squert, and ELSA with their Go equivalents, as these can be difficult to install unless you're using Security Onion (which we don't use).

Any help, feedback, or whatever is always welcomed.

**Comment by cleesmith** [comment]
Actually, I bounce around doing mostly remote jobs (like Upwork and such).
As a programmer I don't a great deal of day-to-day experience with network security monitoring ... it sounds like you do.  
How has elasticsearch handled the volume of alerts/events in your experience?

**Comment by mike-mitchell** [comment]
Its done well so far. We are getting about 14,631,356 documents per day on average. Because we aren't clustering Elasticsearch, we are only using 1 shard with 0 replicas. Performance has been pretty good.

**Comment by cleesmith** [comment]
Mostly I have avoided ES's clusters. Sometimes clients complain about slow searches in ES, but they also did for SOLR and ELSA(mysql) ... it's always because of trying to keep "everything forever". Most of the software I write I test with indexing 60 million documents per day for two weeks, but I have not tested unifiedbeat with that volume as yet.
