### ISSUE TITLE
Unable to parse Control Word or EoMPLS Frames

### ISSUE THREAD

**Issue by rmatulat** [cleesmith/unifiedbeat#12]
Hi,
I recognized that Unifiedbeat is unable to decode control word and/or EoMPLS (Pseudo Wire) frames after the Bottom Of Stack MPLS Frame.
It just expects IPv4 or IPv6 - so following CW or PW frames are causing an "Unable to guess protocol of packet data" error.
Kind regards
Ralf

**Comment by cleesmith** [comment]
That's not something I anticipated or have experience with ... so if you have a fix please feel free to do so and make a pull request. Thanks.

**Comment by rmatulat** [comment]
In that case I first have to deep-dive into Golang.
For our environment I q&d patched the `vendor/github.com/google/gopacket/layers/mpls.go` file, but I guess for a more convenient solution I have to invest some extra time.
I'll have a look at this.
