### ISSUE TITLE
Feature Request: Daemonize

### ISSUE THREAD

**Issue by DigiAngel** [cleesmith/unifiedbeat#13]
Topic :)  maybe change the -d to daemonize or add a -D?  Thank you...this is a great app!

**Comment by cleesmith** [comment]
I no longer actively work on this, so please feel to fork and enhance it.

**Comment by DigiAngel** [comment]
Oh my....ok thank you...wow that's a bummer as this project was just what I was needing :(  Thank you.

**Comment by cleesmith** [comment]
Actually I would recommend using upstart or systemd to daemonize most processes.

**Comment by DigiAngel** [comment]
Will do thanks.  I'm going to fork it and keep it handy...I'm not a 
programmer, but if something breaks in the future could I possibly hit 
you up for help if I get stuck?

**Comment by cleesmith** [comment]
No guarantees, but sure.

**Comment by DigiAngel** [comment]
Thanks....totally get it....you stopped supporting this, last thing you 
need is some clown asking questions about :)  It's going to be a 
learning experience...thank you!
