### ISSUE TITLE
appStats can't work

### ISSUE THREAD

**Issue by AAyyy** [cleesmith/unifiedbeat#15]
when use  u2openappid it dumps like:
like:tatTime="1527172305",appName="HTTP",txBytes="1105",rxBytes="4238"
statTime="1527172305",appName="uri_html",txBytes="1105",rxBytes="4238"
statTime="1527172305",appName="HTTP",txBytes="1785",rxBytes="8359"
statTime="1527172305",appName="uri_html",txBytes="1785",rxBytes="8359"
statTime="1527172305",appName="HTTP",txBytes="24515",rxBytes="110793"

but this tool can't read??
i want to know if it has this func,thx!!!

**Comment by cleesmith** [comment]
Sorry, no it doesn't.
