### ISSUE TITLE
Can't compile/install

### ISSUE THREAD

**Issue by urvile** [cleesmith/unifiedbeat#6]
`src/unifiedbeat/main.go:40: cannot use unifiedbeat.New() (type *unifiedbeat.Unifiedbeat) as type "unifiedbeat/vendor/github.com/elastic/beats/libbeat/beat".Beater in argument to "unifiedbeat/vendor/github.com/elastic/beats/libbeat/beat".Run:
    *unifiedbeat.Unifiedbeat does not implement "unifiedbeat/vendor/github.com/elastic/beats/libbeat/beat".Beater (wrong type for Cleanup method)
        have Cleanup(*"github.com/cleesmith/unifiedbeat/vendor/github.com/elastic/beats/libbeat/beat".Beat) error
        want Cleanup(*"unifiedbeat/vendor/github.com/elastic/beats/libbeat/beat".Beat) error
make: *** [install] Error 2
`
Had a dickens of a time getting the dependencies right.

**Comment by cleesmith** [comment]
If you are new to Go, there is a pre-compiled binary for Linux 64bit platforms ... just click on [releases](https://github.com/cleesmith/unifiedbeat/releases/tag/v2.0.1).

To compile correctly with the **known/tested dependencies** in the **vendor folder**:
- **go version** must be 1.6+
- ensure PATH, GOPATH, vendor settings in ~/.profile:
  - export PATH=$PATH:/usr/local/go/bin
  - export GOPATH=/home/someuser/go  
  - export GO15VENDOREXPERIMENT=1  _(this is the default in Go 1.6+)_
- mkdir -p ~/go/src/github.com/cleesmith
- cd ~/go/src/github.com/cleesmith
- git clone https://github.com/cleesmith/unifiedbeat 
- cd unifiedbeat
- go get github.com/davecgh/go-spew  _(future todo: remove this dependency)_
  - this is used by the Beats for testing
  - this app will **not** compile with later releases of **libbeat**, as Elastic is still developing the beats so there is no way to keep up with all of their releases
  - besides, the vendored release of libbeat included works properly, so I have **frozen** at that release
- **go build**

Hope that helps.

**Comment by cleesmith** [comment]
Retested compiling on:

```
$ uname -a
Linux box 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:    14.04
Codename:   trusty
```

and the process described works.
