### ISSUE TITLE
How to build from source?

### ISSUE THREAD

**Issue by ravi023** [cleesmith/unifiedbeat#7]

**Comment by cleesmith** [comment]
A pre-built Linux 64bit version is [here](https://github.com/cleesmith/unifiedbeat/releases/tag/v2.0.1).
It was built using Go 1.6 and tested on Ubuntu 14.04.3.

To build from source:
- cd $GOPATH
- git clone https://github.com/cleesmith/unifiedbeat
- cd unifiedbeat
- go build

Note: all of the **working dependencies** are included in the **vendor** folder.
